apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multicloud-app
  template:
    metadata:
      labels:
        app: multicloud-app
    spec:
      containers:
      - name: multicloud-app
        image: josesamuel14/multicloud-app:3177fc761d4b4912fe533625dc3b7c3379153dfb
        ports:
        - containerPort: 5000
        env:
        - name: CLOUD_PROVIDER
          value: "local"
