apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multicloud-app
  template:
    metadata:
      labels:
        app: multicloud-app
    spec:
      containers:
      - name: multicloud-app
        image: josesamuel14/multicloud-app:a6e4f22fa56488c6eb943d5e5c3ab096a32927f0
        ports:
        - containerPort: 5000
        env:
        - name: CLOUD_PROVIDER
          value: "local"
