apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multicloud-app
  template:
    metadata:
      labels:
        app: multicloud-app
    spec:
      containers:
      - name: multicloud-app
        image: josesamuel14/multicloud-app:b84d558f36d3ed56cd5748dec999f23ddd0a1949
        ports:
        - containerPort: 5000
        env:
        - name: CLOUD_PROVIDER
          value: "local"
