name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - devops-v2
  repository_dispatch:
    types: [manual-deploy]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest tests/test_app.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            josesamuel14/multicloud-app:latest
            josesamuel14/multicloud-app:${{ github.sha }}